### ISSUE TITLE
import structure

### ISSUE THREAD

**Issue by martinshkreli** [itsnamgyu/block-transformer#2]
/lm_eval/models/__init__.py:

from . import huggingface
from . import block_transformer

there are two ambiguous registrations of the alias.

from . import huggingface
from . import block_transformer_nopad

may work better, but the current code does not work, out-of-the-box

**Comment by raymin0223** [comment]
Hi @martinshkreli,

Thanks for reporting a bug! We resolved this issue with [commit](https://github.com/itsnamgyu/block-transformer/commit/56b5ef016b2ccbfc8ea224041067826c319d4f1d).

In detail, we pretrained our Block Transformers above 420M parameters without applying random-length padding when packing documents.
These models were not trained on blocks containing padding, so during evaluation, the prompts had to be fed without left padding -- using class in `block_transformer_nopad.py`.  

Nevertheless, we confirmed that pretraining with random-length padding improves the robustness of our Block Transformer.
Therefore, we recommend setting both `random_pad_first_block` and `pad_to_block_boundary` to True during packing documents.

**Comment by itsnamgyu** [comment]
The latest commit sets `random_pad_first_block` and `pad_to_block_boundary` to True by default!

Just to clarify, `random_pad_first_block` means adding random left-padding to the first block of each document to support left-side padding during inference. `pad_to_block_boundary` right-pads the last block of each document.

Thanks for the feedback
