### ISSUE TITLE
missing file for example

### ISSUE THREAD

**Issue by martinshkreli** [itsnamgyu/block-transformer#3]
The example:
CUDA_VISIBLE_DEVICES=0 python eval_zero_shot_task.py --config-name=240425_eval_multiple_ckpt configs.hf=["vanilla_31"] batch_size=64

seems to refer to a file that no longer exists. in the conf/eval/ folder there is an "eval_multiple_ckpt.yaml" file. running with this file results in an out-of-bounds error:

ubuntu@mldev:~/shkre2/block-transformer$ CUDA_VISIBLE_DEVICES=0 python eval_zero_shot_task.py --config-name=eval_multiple_ckpt.yaml configs.block=["block_main_b4_5"] batch_size=64
2024-08-22:17:42:03,040 INFO     [config.py:59] PyTorch version 2.4.0 available.
/home/ubuntu/shkre2/block-transformer/myenv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
/home/ubuntu/shkre2/block-transformer/eval_zero_shot_task.py:37: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf/eval", config_name="240425_eval_multiple_ckpt")
/home/ubuntu/shkre2/block-transformer/myenv/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[2024-08-22 17:42:06,349][lm-eval][INFO] - Verbosity set to INFO
Evaluating config: block_main_b4_5
Error executing job with overrides: ['configs.block=[block_main_b4_5]', 'batch_size=64']
Traceback (most recent call last):
  File "/home/ubuntu/shkre2/block-transformer/eval_zero_shot_task.py", line 56, in main
    eval_multiple_ckpt(cfg, eval_logger)
  File "/home/ubuntu/shkre2/block-transformer/eval_zero_shot_task.py", line 327, in eval_multiple_ckpt
    last_ckpt = step_ckpt_dirs[-1]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by itsnamgyu** [comment]
We plan to release checkpoints in 1 week. Please stay tuned!

edit: *In case you were trying to load existing checkpoints, rather than newly trained ones

**Comment by raymin0223** [comment]
Sorry for wrong config names in example. We removed `240425_` from those commands. 

And it looks like an error come from `ckpt_dirs = glob.glob(os.path.join(ckpt_fpath, "checkpoint-*"))`, which fails to load checkpoint paths. 
I assume that you pretrain `block_main_b4_5` shortly and save some intermediate checkpoints. If so, the reason might be `null` values for `ckpt_path` in config files.

Could you test with the following command?
`CUDA_VISIBLE_DEVICES=0 python eval_zero_shot_task.py --config-name=eval_multiple_ckpt.yaml configs.block=["block_main_b4_5"] batch_size=64 ckpt_path=[abs path for your own checkpoints]`

edit: *latest commit will set `ckpt_path` to `SAVE_DIR` automatically!

**Comment by raymin0223** [comment]
Feel free to reopen this issue if you have any further questions :)

**Comment by itsnamgyu** [comment]
@martinshkreli Hey Martin, we uploaded the pretrained checkpoints and added new inference demo code.

Check out the updated README!
