### ISSUE TITLE
token decoder

### ISSUE THREAD

**Issue by guangyuli-uoe** [itsnamgyu/block-transformer#4]
hi,

i want to know the pipeline of summation for token decoder. 
sorry but i did not get details about it from the paper, yet not find it in the codebase. 

best wishes,

**Comment by itsnamgyu** [comment]
Hi, sure no problem. We explain the token decider designs in Appendix F.

> Summation We also consider the summation method used in previous work [74]. Here, the context embeddings are projected to L_B embeddings of dimension D and added to the token embeddings at each input position of the token decoder. This does not benefit from additional computation of the context information in the token decoder.


The code is at `model.token_decoder.base.BaseTokenDecoder. _adapt_forward_inputs_for_summation`

Hope this helps
